### ISSUE TITLE
STL is not as relevant as it used to be.

### ISSUE THREAD

**Issue by Qix-** [vic317yeh/One-Click-to-Be-Pro#15]
I think this repo suffers from an inaccuracy. The standard library is not the STL. Newbies should not be using the STL, but instead the standard library.

I would have thought otherwise if the STL links weren't the only things on the list for C++.

**Comment by vicoyeh** [comment]
Thanks for the feedback! My original intention of creating this list was to help underclassmen in my college getting started in working on side projects and passing internship interviews. C++ STL is very helpful for interviews and competitive programming problems. I could possibility move the STL links to the "programming" section and create a separate link just for C++.

**Comment by Qix-** [comment]
As an interviewer, if you choose to use C++ in your interview and don't know the standard library from the STL, you're not going to be getting very far. Like I said, the STL isn't used hardly at all anymore. You're going to want to find a "one click" guide to the C++ standard library.

Just a thought.

**Comment by awelm** [comment]
I totally disagree with you @Qix-. First of all, many people (including very successful authors of C++ books) use the terms STL and standard library interchangeably. Confusing these two terms says absolutely nothing about your ability; rather it says which book you read to learn C++. Second of all, the STL is used **heavily** by students all across the country during their internship interviews. Knowledge of the STL allows students to demonstrate their understanding of data structures tradeoffs without actually implementing these data structures. The author of  "Cracking the Coding Interview", arguably the best book written for interview preparation, **strongly** recommends that you know the STL inside-out to ace your interviews. Maybe the STL isn't used much in the industry, but from a college student's point of view it's used a hell of a lot.

**Comment by Qix-** [comment]
[You literally cannot be more wrong](http://stackoverflow.com/questions/5205491/whats-this-stl-vs-c-standard-library-fight-all-about). STL is hardly used at all and there is little reason to learn it anymore. Students learning about the actual STL versus the standard library _are doing themselves a disservice_.

But hey this is your repository. I'll personally stick to the Awesome lists :+1:.
