### ISSUE TITLE
Repo name is misleading

### ISSUE THREAD

**Issue by fkingn00bGG** [vic317yeh/One-Click-to-Be-Pro#17]

**Comment by btn0s** [comment]
what was your expectation?

**Comment by TwinProduction** [comment]
Honestly the title is misleading. I think it should be changed to something like: Knowledge is power: programming edition. 
As it is, the title sounds like an advertisement, not that there's anything wrong with that :P

**Comment by btn0s** [comment]
Misleading implies that it doesn't meet the expectation it sets... what was your expectation?

**Comment by TwinProduction** [comment]
To click once and become a pro.

**Comment by btn0s** [comment]
Then the fault is yours, friend.

**Comment by spencertabino** [comment]
I think that it is unreasonable to expect to click once and become a pro at anything other than learning how to click once.

Personally, I think the repo name is fine.

**Comment by btn0s** [comment]
@spencertabino +1 exactly.

**Comment by TwinProduction** [comment]
Well, that one time I clicked on an image that told me I was the millionth visitor and I won 5000$..

Needless to say, I didn't win anything :(

**Comment by vic317yeh** [comment]
I used the title "One Click to Be Pro" when I first uploaded the list as a text file on our fb cs group 6 months ago. The title was catchy and got many students interested in learning new tech. 

Since many people enjoyed the original list of resources, I decided to share this list on hacker news and had no ideas how it got so popular. Since many people are now contributing to the list, I'm fine with changing the title to avoid issues like this. 

Open to suggestions :octocat:

**Comment by spencertabino** [comment]
I guess you could change the repo name, but, at this point, I don't know what you would change it to. It's different enough from the `x-awesome` lists to be its own thing, and I kind of like the name anyways.

This is a neat project, though. Good job!

**Comment by vic317yeh** [comment]
@spencertabino Thanks!

**Comment by fkingn00bGG** [comment]
Perhaps place a disclaimer stating reading one book will not make you a professional developer. It takes many hundreds of hours of practice to be half decent.

**Comment by vic317yeh** [comment]
@fkingn00bGG Totally agree. I put the sentence "All you need is one click to become a pro" as a joke initially, but I guess it's time to make this repo more official. Thanks for the suggestion :)

**Comment by btn0s** [comment]
@fkingn00bGG if you know that there's no need for a disclaimer........

**Comment by fkingn00bGG** [comment]
@btn0s What have we to lose from adding a disclaimer? Maybe it is redundant, at worst case we risk sounding "uncool". But this has exploded in popularity and undoubtedly it will start appearing in google searches where completely new people to programming will stumble upon this. Think about how they might interpret this repo title.

**Comment by btn0s** [comment]
@fkingn00bGG why does it matter how they interpret the title? The content is what matters, and no matter if they think this is some sort of magic or not... it's impossible to "one-click master" anything. However they interpret it is up to them, but the title gets people here and to me that's a sign of good naming.

You act like the title really would convince someone that one-click mastery is possible at all... and anyone with any sort of common sense should know it's not. Get over the title and go learn.

**Comment by btn0s** [comment]
@vic317yeh can we close this? Pointless complaints because people can't see past a title aren't the point of github issues. 

Anyone who needs help understanding the title should read about sales copy, branding, and marketing... all of which I'll be happy to go grab some good links to throw in here.

**Comment by vic317yeh** [comment]
Ok, I'm going to close this issue for now. It is hard for me to see people arguing over the title. I see how the title can be misleading and will find a way to address this this issue properly in the doc. I'm thinking about rephrasing the description and make it sound more realistic and formal. This seems like the optimal solution to me. I've been currently pretty busy with other work, but will find a time soon to make the content less ambiguous.

**Comment by btn0s** [comment]
@vic317yeh it's seriously a made-up problem man. The content is what matters :)

Haters gonna hate. You just keep up the good work, don't let this take up your time.
